name: build and deploy

on:
  push:
  workflow_dispatch:

# jobs:
#   pre-job:
#     uses: bbhupati/poc-action-templates/.github/workflows/set-env.yml@master
#   npm:
#     needs: pre-job
#     uses: bbhupati/poc-action-templates/.github/workflows/npm-build.yml@master
#   docker:
#     needs: [pre-job,npm]
#     uses: bbhupati/poc-action-templates/.github/workflows/docker-build-push.yml@master


name: Deployment

on:
  push:
    branches:
      - main
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/dev' && 'dev' || 'unknown' }}
    steps:
      - name: deploy
        # ...deployment-specific steps

