# name: build and deploy

# on:
#   push:
#   workflow_dispatch:

# jobs:
#   pre-job:
#     uses: bbhupati/poc-action-templates/.github/workflows/values.yml@master
#   npm:
#     needs: pre-job
#     uses: bbhupati/poc-action-templates/.github/workflows/npm-build.yml@master
#   docker:
#     needs: [pre-job,npm]
#     uses: bbhupati/poc-action-templates/.github/workflows/docker-build-push.yml@master

on:
  push:
  workflow_dispatch:

jobs:
  download-secret:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev  # Change this to the desired environment (e.g., dev, qa, prod)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          # Choose the secret based on the environment
          case "${{ env.ENVIRONMENT }}" in
            "dev")
              echo "${{ vars.ACR_REGISTRY_DEV }}" > ./secret-file.txt
              ;;
            "qa")
              echo "${{ vars.ACR_REGISTRY_STAGING }}" > ./secret-file.txt
              ;;
            "prod")
              echo "${{ vars.ACR_REGISTRY_PROD }}" > ./secret-file.txt
              ;;
            *)
              echo "Invalid environment specified"
              exit 1
              ;;
          esac

      - name: Display the downloaded secret file
        run: cat ./secret-file.txt
