# name: build and deploy

# on:
#   push:
#   workflow_dispatch:

# jobs:
#   pre-job:
#     uses: bbhupati/poc-action-templates/.github/workflows/values.yml@master
#   npm:
#     needs: pre-job
#     uses: bbhupati/poc-action-templates/.github/workflows/npm-build.yml@master
#   docker:
#     needs: [pre-job,npm]
#     uses: bbhupati/poc-action-templates/.github/workflows/docker-build-push.yml@master

on:
  push:
  workflow_dispatch:

jobs:
  download-secret:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          # Set the secret value to an environment variable
          echo "${{ vars.ACR_REGISTRY }}" > ./secret-file.txt

      - name: Display the downloaded secret file
        run: cat ./secret-file.txt

