name: Build and Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read .env file and set environment variables
        run: |
          ls -l
          cat dev-vars.env
          echo "$(cat dev-vars.env)" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo "Loaded .env into environment variables"
      
      - name: Display loaded environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"
          
      # Continue with your build and deployment steps here
