# name: Build and Deploy

# on:
#   push:
#   workflow_dispatch:

#   docker-build-push:
#     runs-on: ubuntu-latest
#     needs: [set-environment]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Read environment file and set environment variables
#         run: |
#           ENV_FILE=".github/workflows/${{ needs.set-environment.outputs.environment_type }}-vars.env"
#           cat $ENV_FILE >> $GITHUB_ENV
#           echo "Loaded $ENV_FILE into environment variables"
#       - name: Display loaded environment variables
#         run: |
#           echo "API_URL=$API_URL"
#           echo "DATABASE_URL=$DATABASE_URL"

#   update-app-service-config:
#     runs-on: ubuntu-latest
#     needs: [set-environment]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Read environment file and set environment variables
#         run: |
#           ENV_FILE=".github/workflows/${{ needs.set-environment.outputs.environment_type }}-vars.env"
#           cat $ENV_FILE >> $GITHUB_ENV
#           echo "Loaded $ENV_FILE into environment variables"
#       - name: Display loaded environment variables
#         run: |
#           echo "API_URL=$API_URL"
#           echo "DATABASE_URL=$DATABASE_URL"


# on:
#   push:
#     branches: ['*']

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "test=$(date +"%d-%m-%Y")-asdfads223" >> $GITHUB_OUTPUT
#       - id: step2
#         run: echo "test=world" >> $GITHUB_OUTPUT
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}




name: Call a reusable workflow and use its outputs

on:
  push:
  workflow_dispatch:

jobs:
  npm:
    uses: bbhupati/poc-action-templates/.github/workflows/npm-build.yml@master
  docker:
    uses: bbhupati/poc-action-templates/.github/workflows/docker-build-push.yml@master
