name: Build and Deploy

on:
  push:
    branches:
      - "*"

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment based on branch name
        id: set_env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
            echo "environment=dev"
          elif [[ ${{ github.ref }} == "refs/heads/qa" ]]; then
            echo "environment=qa"
          elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            echo "environment=prod"
          else
            echo "environment=unknown environment"
          fi
          echo "env is $environment, ${{ env.environment }}, ${{ needs.set-environment.outputs.environment }}"
        continue-on-error: true

  npm-build-test:
    runs-on: ubuntu-latest
    needs: [set-environment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read environment file and set environment variables
        run: |
          echo "env is $environment, ${{env.environment}}, ${{ needs.set-environment.outputs.environment }}"
          ENV_FILE=".github/workflows/${{ needs.set-environment.outputs.environment }}-vars.env"
          cat $ENV_FILE >> $GITHUB_ENV
          echo "Loaded $ENV_FILE into environment variables"
      - name: Display loaded environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [set-environment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read environment file and set environment variables
        run: |
          ENV_FILE=".github/workflows/${{ needs.set-environment.outputs.environment }}-vars.env"
          cat $ENV_FILE >> $GITHUB_ENV
          echo "Loaded $ENV_FILE into environment variables"
      - name: Display loaded environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"

  update-app-service-config:
    runs-on: ubuntu-latest
    needs: [set-environment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read environment file and set environment variables
        run: |
          ENV_FILE=".github/workflows/${{ needs.set-environment.outputs.environment }}-vars.env"
          cat $ENV_FILE >> $GITHUB_ENV
          echo "Loaded $ENV_FILE into environment variables"
      - name: Display loaded environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"
