on: [push]

jobs:
  npm-build-test:
    uses: ./templates/npm-build.yml@master

  docker-build-push:
    uses: ./templates/docker-build-push.yml@master  # No version specified here
    secrets: inherit
    needs: [npm-build-test]
    if: ${{ always() && contains(needs.*.result, 'success') }}
