on: [push]

jobs:
  set-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine environment based on branch name
        id: set_env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == "refs/heads/qa" ]]; then
            echo "environment=qa" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            echo "environment=prod" >> $GITHUB_ENV
          else
            echo "environment=unknown" >> $GITHUB_ENV
          fi

      - name: Read environment file and set environment variables
        run: |
          ENV_FILE=".github/workflows/${{ env.environment }}-vars.env"
          cat $ENV_FILE >> $GITHUB_ENV

  npm-build-test:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"
      # ... rest of the job steps

  docker-build-push:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"
      # ... rest of the job steps

  update-app-service-config:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display environment variables
        run: |
          echo "API_URL=$API_URL"
          echo "DATABASE_URL=$DATABASE_URL"
      # ... rest of the job steps
